-- =====================================================
-- KREYÒL DICTIONARY — Day 2 Bulk Seed
-- 500 words across 12 categories
-- Generated manually from Haitian Creole corpus
-- =====================================================

BEGIN;

-- ======== EVERYDAY (80 words) ========
INSERT INTO public.dictionary_words (word, word_creole, pronunciation, translation_english, translation_french, translation_spanish, part_of_speech, gender, example_sentence, example_translation, category, difficulty, tags, day_added) VALUES
('Sun', 'Solèy', 'so-le-ye', 'Sun', 'Soleil', 'Sol', 'noun', 'm', 'Solèy la fè cho.', 'The sun is hot.', 'nature', 'beginner', ARRAY['nature','weather'], 2),
('Moon', 'Lalin', 'la-lin', 'Moon', 'Lune', 'Luna', 'noun', 'm', 'Lalin an fè klere.', 'The moon is bright.', 'nature', 'beginner', ARRAY['nature','weather'], 2),
('Water', 'Dlo', 'dlo', 'Water', 'Eau', 'Agua', 'noun', 'm', 'Dlo a frèch.', 'The water is fresh.', 'everyday', 'beginner', ARRAY['survival','essential'], 2),
('Fire', 'Dife', 'di-fe', 'Fire', 'Feu', 'Fuego', 'noun', 'm', 'Dife a blink.', 'The fire is burning.', 'everyday', 'beginner', ARRAY['survival'], 2),
('Earth', 'Latè', 'la-te', 'Earth / Ground', 'Terre', 'Tierra', 'noun', 'm', 'Latè a gen anpil wòch.', 'The ground has many rocks.', 'nature', 'beginner', ARRAY['nature'], 2),
('Air', 'Lè', 'le', 'Air / Wind', 'Air', 'Aire', 'noun', 'm', 'Lè a cho.', 'The air is hot.', 'nature', 'beginner', ARRAY['nature'], 2),
('Rain', 'Lapli', 'lap-li', 'Rain', 'Pluie', 'Lluvia', 'noun', 'm', 'Lapli ap tonbe.', 'Rain is falling.', 'nature', 'beginner', ARRAY['weather'], 2),
('Road', 'Wout', 'wout', 'Road / Path', 'Route', 'Camino', 'noun', 'm', 'Wout la long.', 'The road is long.', 'everyday', 'beginner', ARRAY['travel'], 2),
('Door', 'Pòt', 'pot', 'Door', 'Porte', 'Puerta', 'noun', 'f', 'Pòt la fèmen.', 'The door is closed.', 'everyday', 'beginner', ARRAY['house'], 2),
('Window', 'Fennet', 'fe-ne', 'Window', 'Fenêtre', 'Ventana', 'noun', 'f', 'Fennet la louvwi.', 'The window is open.', 'everyday', 'beginner', ARRAY['house'], 2),
('Bed', 'Liyann', 'li-yan', 'Bed', 'Lit', 'Cama', 'noun', 'm', 'Liyann nan bèl.', 'The bed is nice.', 'everyday', 'beginner', ARRAY['house'], 2),
('Table', 'Tab', 'tab', 'Table', 'Table', 'Mesa', 'noun', 'f', 'Tab la wo.', 'The table is high.', 'everyday', 'beginner', ARRAY['house'], 2),
('Chair', 'Chèz', 'shez', 'Chair', 'Chaise', 'Silla', 'noun', 'f', 'Chèz la konfòt.', 'The chair is comfortable.', 'everyday', 'beginner', ARRAY['house'], 2),
('Bag', 'Sak', 'sak', 'Bag / Sack', 'Sac', 'Bolsa', 'noun', 'm', 'Sak la lou.', 'The bag is heavy.', 'everyday', 'beginner', ARRAY['shopping'], 2),
('Book', 'Liv', 'liv', 'Book', 'Livre', 'Libro', 'noun', 'm', 'Liv la enteresan.', 'The book is interesting.', 'education', 'beginner', ARRAY['reading'], 2),
('Paper', 'Papye', 'pa-pye', 'Paper', 'Papier', 'Papel', 'noun', 'm', 'Papye a blan.', 'The paper is white.', 'everyday', 'beginner', ARRAY['office'], 2),
('Car', 'Machin', 'ma-shin', 'Car', 'Voiture', 'Carro', 'noun', 'm', 'Machin nan nèf.', 'The car is new.', 'everyday', 'beginner', ARRAY['transport'], 2),
('Phone', 'Telefòn', 'te-le-fon', 'Phone', 'Téléphone', 'Teléfono', 'noun', 'm', 'Telefòn nan sonnen.', 'The phone is ringing.', 'everyday', 'beginner', ARRAY['tech'], 2),
('Hand', 'Men', 'men', 'Hand', 'Main', 'Mano', 'noun', 'f', 'Men mwen fè mal.', 'My hand hurts.', 'everyday', 'beginner', ARRAY['body'], 2),
('Head', 'Tèk', 'tek', 'Head', 'Tête', 'Cabeza', 'noun', 'm', 'Tèk mwen fè mal.', 'My head hurts.', 'everyday', 'beginner', ARRAY['body'], 2),
('Eye', 'Je', 'je', 'Eye', 'Oeil', 'Ojo', 'noun', 'm', 'Je mwen pa wè byen.', 'My eye does not see well.', 'everyday', 'beginner', ARRAY['body'], 2),
('Ear', 'Zòrèy', 'zo-rey', 'Ear', 'Oreille', 'Oreja', 'noun', 'f', 'Zòrèy mwen chenn.', 'My ear is itching.', 'everyday', 'beginner', ARRAY['body'], 2),
('Mouth', 'Bouch', 'bouch', 'Mouth', 'Bouche', 'Boca', 'noun', 'm', 'Bouch la ap manje.', 'The mouth is eating.', 'everyday', 'beginner', ARRAY['body'], 2),
('Heart', 'Kè', 'ke', 'Heart', 'Coeur', 'Corazón', 'noun', 'm', 'Kè mwen ap bat fò.', 'My heart is beating fast.', 'everyday', 'beginner', ARRAY['body','emotions'], 2),
('Foot', 'Pye', 'pye', 'Foot / Leg', 'Pied', 'Pie', 'noun', 'm', 'Pye mwen fè mal.', 'My foot hurts.', 'everyday', 'beginner', ARRAY['body'], 2),
('Body', 'Kò', 'ko', 'Body', 'Corps', 'Cuerpo', 'noun', 'm', 'Kò mwen fatigue.', 'My body is tired.', 'everyday', 'beginner', ARRAY['body'], 2),
('Blood', 'San', 'san', 'Blood', 'Sang', 'Sangre', 'noun', 'm', 'San an koule.', 'Blood is flowing.', 'health', 'intermediate', ARRAY['body'], 2),
('Name', 'Non', 'non', 'Name', 'Nom', 'Nombre', 'noun', 'm', 'Non ou seisa?', 'What is your name?', 'everyday', 'beginner', ARRAY['essential'], 2),
('Face', 'Figi', 'fi-gi', 'Face', 'Visage', 'Cara', 'noun', 'm', 'Figi ou bèl.', 'Your face is beautiful.', 'everyday', 'beginner', ARRAY['body'], 2),
('Hair', 'Cheve', 'she-ve', 'Hair', 'Cheveux', 'Cabello', 'noun', 'm', 'Cheve ou long.', 'Your hair is long.', 'everyday', 'beginner', ARRAY['body'], 2),
('Skin', 'Po', 'po', 'Skin', 'Peau', 'Piel', 'noun', 'm', 'Po mwen klere.', 'My skin is light.', 'everyday', 'beginner', ARRAY['body'], 2),
('Bone', 'Zo', 'zo', 'Bone', 'Os', 'Hueso', 'noun', 'm', 'Zo an fè mal.', 'The bone hurts.', 'health', 'intermediate', ARRAY['body'], 2),
('Stomach', 'Vant', 'van', 'Stomach', 'Estomac', 'Estómago', 'noun', 'm', 'Vant mwen ap fè mal.', 'My stomach hurts.', 'health', 'beginner', ARRAY['body'], 2),
('Town', ' vil', 'vil', 'Town / City', 'Ville', 'Ciudad', 'noun', 'f', 'Vil la gwo.', 'The city is big.', 'everyday', 'beginner', ARRAY['geography'], 2),
('Country', 'Peyi', 'pe-yi', 'Country', 'Pays', 'País', 'noun', 'm', 'Peyi an bèl.', 'The country is beautiful.', 'everyday', 'beginner', ARRAY['geography'], 2),
('Village', 'Peyi', 'pe-yi', 'Village', 'Village', 'Pueblo', 'noun', 'm', 'Peyi an pi byèl.', 'The village is very beautiful.', 'everyday', 'beginner', ARRAY['geography'], 2),
('School', 'Lekòl', 'le-kol', 'School', 'École', 'Escuela', 'noun', 'm', 'Timoun nan ale nan lekol.', 'The child is going to school.', 'education', 'beginner', ARRAY['learning'], 2),
('Church', 'Legliz', 'le-gliz', 'Church', 'Église', 'Iglesia', 'noun', 'f', 'Legliz la bèl.', 'The church is beautiful.', 'everyday', 'beginner', ARRAY['religion'], 2),
('God', 'Bondye', 'bon-dye', 'God', 'Dieu', 'Dios', 'noun', 'm', 'Bondye bon.', 'God is good.', 'everyday', 'beginner', ARRAY['religion'], 2),
('Devil', 'Satan', 'sa-tan', 'Devil', 'Diable', 'Diablo', 'noun', 'm', 'Satan mal.', 'The devil is evil.', 'everyday', 'intermediate', ARRAY['religion'], 2),
('Heaven', 'Latè', 'la-te', 'Heaven', 'Ciel', 'Cielo', 'noun', 'm', 'Latè se yon bèl kote.', 'Heaven is a beautiful place.', 'everyday', 'intermediate', ARRAY['religion'], 2),
('Life', 'Lavi', 'la-vi', 'Life', 'Vie', 'Vida', 'noun', 'm', 'Lavi a di.', 'Life is hard.', 'everyday', 'beginner', ARRAY['essential'], 2),
('Death', 'Lanmò', 'lan-mo', 'Death', 'Mort', 'Muerte', 'noun', 'f', 'Lanmò pa janm pale.', 'Death never speaks.', 'everyday', 'intermediate', ARRAY['serious'], 2),
('Word', 'Para', 'pa-ra', 'Word', 'Mot', 'Palabra', 'noun', 'm', 'Para a vre.', 'The word is true.', 'everyday', 'beginner', ARRAY['language'], 2),
('Language', 'Lang', 'lang', 'Language', 'Langue', 'Idioma', 'noun', 'm', 'Lang kreyòl bèl.', 'The Kreyòl language is beautiful.', 'everyday', 'beginner', ARRAY['language'], 2),
('Voice', 'Vwa', 'vwa', 'Voice', 'Voix', 'Voz', 'noun', 'f', 'Vwa ou bèl.', 'Your voice is beautiful.', 'everyday', 'beginner', ARRAY['communication'], 2),
('Letter', 'Lèt', 'let', 'Letter', 'Lettre', 'Carta', 'noun', 'f', 'Lèt la ap tann.', 'The letter is waiting.', 'everyday', 'beginner', ARRAY['communication'], 2),
('Message', 'Mesaj', 'me-sazh', 'Message', 'Message', 'Mensaje', 'noun', 'm', 'Mesaj la te klè.', 'The message was clear.', 'everyday', 'beginner', ARRAY['communication'], 2),
('News', 'Nouvèl', 'nou-vel', 'News', 'Nouvelles', 'Noticias', 'noun', 'm', 'Nouvèl la byen.', 'The news is good.', 'everyday', 'beginner', ARRAY['media'], 2),
('Story', 'Istwa', 'is-to-ya', 'Story', 'Histoire', 'Historia', 'noun', 'm', 'Istwa a enteresan.', 'The story is interesting.', 'everyday', 'beginner', ARRAY['culture'], 2),
('Truth', 'Vérité', 've-ri-te', 'Truth', 'Vérité', 'Verdad', 'noun', 'f', 'Vérité ap genyen.', 'Truth wins.', 'everyday', 'beginner', ARRAY['values'], 2),
('Lie', 'Mensonj', 'men-sonzh', 'Lie', 'Mensonge', 'Mentira', 'noun', 'm', 'Mensonj pa dwa.', 'A lie is not right.', 'everyday', 'beginner', ARRAY['values'], 2),
('Right', 'Dwa', 'dwa', 'Right', 'Droit', 'Derecho', 'noun', 'm', 'Dwa mwen an.', 'My right.', 'everyday', 'intermediate', ARRAY['values'], 2),
('Left', 'Goch', 'goch', 'Left', 'Gauche', 'Izquierda', 'adj', 'mf', 'Kotche goch la.', 'The left side.', 'everyday', 'beginner', ARRAY['directions'], 2),
('Up', 'Anlè', 'an-le', 'Up / Above', 'En haut', 'Arriba', 'adv', 'mf', 'Ale anlè.', 'Go up.', 'everyday', 'beginner', ARRAY['directions'], 2),
('Down', 'Anba', 'an-ba', 'Down / Below', 'En bas', 'Abajo', 'adv', 'mf', 'Ale anba.', 'Go down.', 'everyday', 'beginner', ARRAY['directions'], 2),
('Inside', 'Andidan', 'an-di-dan', 'Inside', 'Dedans', 'Adentro', 'adv', 'mf', 'Ale andidan.', 'Go inside.', 'everyday', 'beginner', ARRAY['directions'], 2),
('Outside', 'Deye', 'de-ye', 'Outside', 'Dehors', 'Afuera', 'adv', 'mf', 'Ale deye.', 'Go outside.', 'everyday', 'beginner', ARRAY['directions'], 2),
('Far', 'Lwen', 'lwen', 'Far', 'Loin', 'Lejos', 'adj', 'mf', 'Kay la lwen.', 'The house is far.', 'everyday', 'beginner', ARRAY['distance'], 2),
('Near', 'Pre', 'pre', 'Near / Close', 'Près', 'Cerca', 'adj', 'mf', 'Machin nan pre.', 'The car is near.', 'everyday', 'beginner', ARRAY['distance'], 2),
('Big', 'Gwo', 'gwo', 'Big / Large', 'Grand', 'Grande', 'adj', 'mf', 'Vil la gwo.', 'The city is big.', 'everyday', 'beginner', ARRAY['size'], 2),
('Small', 'Piti', 'pi-ti', 'Small', 'Petit', 'Pequeño', 'adj', 'mf', 'Timoun nan piti.', 'The child is small.', 'everyday', 'beginner', ARRAY['size'], 2),
('Long', 'Long', 'long', 'Long', 'Long', 'Largo', 'adj', 'mf', 'Wout la long.', 'The road is long.', 'everyday', 'beginner', ARRAY['size'], 2),
('Short', 'Kou', 'kou', 'Short', 'Court', 'Corto', 'adj', 'mf', 'Tan nan kou.', 'The time is short.', 'everyday', 'beginner', ARRAY['size'], 2),
('Heavy', 'Lou', 'lou', 'Heavy', 'Lourd', 'Pesado', 'adj', 'mf', 'Sak la lou.', 'The bag is heavy.', 'everyday', 'beginner', ARRAY['weight'], 2),
('Light', 'Lè', 'le', 'Light (weight)', 'Léger', 'Ligero', 'adj', 'mf', 'Sak la lè.', 'The bag is light.', 'everyday', 'beginner', ARRAY['weight'], 2),
('New', 'Nèf', 'nef', 'New', 'Nouveau', 'Nuevo', 'adj', 'mf', 'Machin nan nèf.', 'The car is new.', 'everyday', 'beginner', ARRAY['age'], 2),
('Old', 'Vye', 'vye', 'Old', 'Vieux', 'Viejo', 'adj', 'mf', 'Kay la vye.', 'The house is old.', 'everyday', 'beginner', ARRAY['age'], 2),
('Good', 'Bon', 'bon', 'Good', 'Bon', 'Bueno', 'adj', 'mf', 'Moun nan bon.', 'The person is good.', 'everyday', 'beginner', ARRAY['quality'], 2),
('Bad', 'Move', 'mo-ve', 'Bad', 'Mauvais', 'Malo', 'adj', 'mf', 'Sa a move.', 'That is bad.', 'everyday', 'beginner', ARRAY['quality'], 2),
('Beautiful', 'Bèl', 'bel', 'Beautiful', 'Beau', 'Bonito', 'adj', 'mf', 'Fanm nan bèl.', 'The woman is beautiful.', 'everyday', 'beginner', ARRAY['quality'], 2),
('Ugly', 'Lèd', 'led', 'Ugly', 'Laid', 'Feo', 'adj', 'mf', 'Moun nan lèd.', 'The person is ugly.', 'everyday', 'intermediate', ARRAY['quality'], 2),
('Strong', 'Fò', 'fo', 'Strong', 'Fort', 'Fuerte', 'adj', 'mf', 'Gason nan fò.', 'The man is strong.', 'everyday', 'beginner', ARRAY['quality'], 2),
('Weak', 'Fèb', 'feb', 'Weak', 'Faible', 'Débil', 'adj', 'mf', 'Moun nan fèb.', 'The person is weak.', 'everyday', 'intermediate', ARRAY['quality'], 2),
('Hot', 'Cho', 'cho', 'Hot', 'Chaud', 'Caliente', 'adj', 'mf', 'Dlo a cho.', 'The water is hot.', 'everyday', 'beginner', ARRAY['temperature'], 2),
('Cold', 'Frèch', 'fresh', 'Cold', 'Froid', 'Frío', 'adj', 'mf', 'Dlo a frèch.', 'The water is cold.', 'everyday', 'beginner', ARRAY['temperature'], 2),
('Dry', 'Sek', 'sek', 'Dry', 'Sec', 'Seco', 'adj', 'mf', 'Latè a sek.', 'The ground is dry.', 'nature', 'intermediate', ARRAY['weather'], 2),
('Wet', 'Mouye', 'mou-ye', 'Wet', 'Mouillé', 'Mojado', 'adj', 'mf', 'Rad la mouye.', 'The clothes are wet.', 'everyday', 'intermediate', ARRAY['weather'], 2),
('Clean', 'Nèt', 'net', 'Clean', 'Propre', 'Limpio', 'adj', 'mf', 'Kay la nèt.', 'The house is clean.', 'everyday', 'beginner', ARRAY['condition'], 2),
('Dirty', 'Sal', 'sal', 'Dirty', 'Sale', 'Sucio', 'adj', 'mf', 'Rad la sal.', 'The clothes are dirty.', 'everyday', 'beginner', ARRAY['condition'], 2),
('White', 'Blan', 'blan', 'White', 'Blanc', 'Blanco', 'adj', 'mf', 'Dlo a blan.', 'The water is white.', 'colors', 'beginner', ARRAY['colors'], 2),
('Black', 'Nwa', 'nwa', 'Black', 'Noir', 'Negro', 'adj', 'mf', 'Nwa a fonse.', 'Black is dark.', 'colors', 'beginner', ARRAY['colors'], 2),
('Red', 'Wouj', 'wouzh', 'Red', 'Rouge', 'Rojo', 'adj', 'mf', 'Sen an wouj.', 'The blood is red.', 'colors', 'beginner', ARRAY['colors'], 2),
('Blue', 'Bli', 'bli', 'Blue', 'Bleu', 'Azul', 'adj', 'mf', 'Lalo a bli.', 'The sky is blue.', 'colors', 'beginner', ARRAY['colors'], 2),
('Green', 'Vè', 've', 'Green', 'Vert', 'Verde', 'adj', 'mf', 'Pyebwa a vè.', 'The tree is green.', 'colors', 'beginner', ARRAY['colors'], 2),
('Yellow', 'Jòn', 'zhon', 'Yellow', 'Jaune', 'Amarillo', 'adj', 'mf', 'Dlo a jòn.', 'The water is yellow.', 'colors', 'beginner', ARRAY['colors'], 2),
('Orange', 'Oranj', 'o-ranz', 'Orange', 'Orange', 'Naranja', 'adj', 'mf', 'Fwi la oranj.', 'The fruit is orange.', 'colors', 'beginner', ARRAY['colors'], 2);

-- ======== FOOD (60 words) ========
INSERT INTO public.dictionary_words (word, word_creole, pronunciation, translation_english, translation_french, translation_spanish, part_of_speech, gender, example_sentence, example_translation, category, difficulty, tags, day_added) VALUES
('Corn', 'Mil', 'mil', 'Corn', 'Maïs', 'Maíz', 'noun', 'm', 'Mil la fè byen.', 'The corn is good.', 'food', 'beginner', ARRAY['food','agriculture'], 2),
('Banana', 'Bannann', 'ban-nan', 'Banana', 'Banane', 'Banano', 'noun', 'm', 'Bannann la dous.', 'The banana is sweet.', 'food', 'beginner', ARRAY['food','fruit'], 2),
('Mango', 'Mango', 'man-go', 'Mango', 'Mangue', 'Mango', 'noun', 'm', 'Mango a fin ranje.', 'The mango is ripe.', 'food', 'beginner', ARRAY['food','fruit'], 2),
('Guava', 'Gwayav', 'gwa-yav', 'Guava', 'Goyave', 'Guayaba', 'noun', 'm', 'Gwayav la bon.', 'The guava is good.', 'food', 'intermediate', ARRAY['food','fruit'], 2),
('Coconut', 'Kokoye', 'ko-ko-ye', 'Coconut', 'Noix de coco', 'Coco', 'noun', 'm', 'Kokoye a gen dlo.', 'The coconut has water.', 'food', 'beginner', ARRAY['food','fruit'], 2),
('Papaya', 'Papay', 'pa-pai', 'Papaya', 'Papaye', 'Papaya', 'noun', 'm', 'Papay la fin mouri.', 'The papaya is ripe.', 'food', 'intermediate', ARRAY['food','fruit'], 2),
('Pineapple', 'Anana', 'a-na-na', 'Pineapple', 'Ananas', 'Piña', 'noun', 'm', 'Anana a pi.', 'The pineapple is sour.', 'food', 'intermediate', ARRAY['food','fruit'], 2),
('Lemon', 'Sitwon', 'sit-won', 'Lemon', 'Citron', 'Limón', 'noun', 'm', 'Sitwon la pi.', 'The lemon is sour.', 'food', 'intermediate', ARRAY['food','fruit'], 2),
('Sweet', 'Dous', 'dous', 'Sweet', 'Sucré', 'Dulce', 'adj', 'mf', 'Dous an fè.', 'Candy is sweet.', 'food', 'beginner', ARRAY['taste'], 2),
('Sour', 'Pi', 'pi', 'Sour', 'Aigre', 'Agrio', 'adj', 'mf', 'Sitwon la pi.', 'The lemon is sour.', 'food', 'beginner', ARRAY['taste'], 2),
('Spicy', 'Pikan', 'pi-kan', 'Spicy / Hot', 'Épice', 'Picante', 'adj', 'mf', 'Sos la pikan.', 'The sauce is spicy.', 'food', 'beginner', ARRAY['taste'], 2),
('Salt', 'Sèl', 'sel', 'Salt', 'Sel', 'Sal', 'noun', 'm', 'Sèl la ase.', 'The salt is enough.', 'food', 'beginner', ARRAY['seasoning'], 2),
('Pepper', 'Piman', 'pi-man', 'Pepper', 'Poivre', 'Pimienta', 'noun', 'm', 'Piman an fèk ap.', 'The pepper is new.', 'food', 'beginner', ARRAY['seasoning'], 2),
('Oil', 'Lwil', 'lwil', 'Oil', 'Huile', 'Aceite', 'noun', 'm', 'Lwil a kouche.', 'The oil is thick.', 'food', 'beginner', ARRAY['cooking'], 2),
('Butter', 'Bè', 'be', 'Butter', 'Beurre', 'Mantequilla', 'noun', 'm', 'Bè a fè.', 'Butter is good.', 'food', 'beginner', ARRAY['dairy'], 2),
('Milk', 'Laktòz', 'lak-toz', 'Milk', 'Lait', 'Leche', 'noun', 'm', 'Laktòz la frech.', 'The milk is fresh.', 'food', 'beginner', ARRAY['dairy'], 2),
('Egg', 'Ze', 'ze', 'Egg', 'Oeuf', 'Huevo', 'noun', 'm', 'Ze a fè byen.', 'The egg is good.', 'food', 'beginner', ARRAY['protein'], 2),
('Meat', 'Vyan', 'vyan', 'Meat', 'Viande', 'Carne', 'noun', 'm', 'Vyan an bèl.', 'The meat is beautiful.', 'food', 'beginner', ARRAY['protein'], 2),
('Beef', 'Bef', 'bef', 'Beef', 'Boeuf', 'Res', 'noun', 'm', 'Bef la kwit.', 'The beef is cooked.', 'food', 'beginner', ARRAY['protein'], 2),
('Pork', 'Kochon', 'ko-shon', 'Pork', 'Porc', 'Cerdo', 'noun', 'm', 'Kochon an fè byen.', 'Pork is good.', 'food', 'beginner', ARRAY['protein'], 2),
('Goat', 'Chèv', 'shev', 'Goat', 'Chèvre', 'Cabra', 'noun', 'f', 'Chèv nan ap manje.', 'The goat is eating.', 'food', 'intermediate', ARRAY['animal'], 2),
('Dog', 'Chen', 'shen', 'Dog', 'Chien', 'Perro', 'noun', 'm', 'Chen nan ap abwa.', 'The dog is barking.', 'everyday', 'beginner', ARRAY['animal'], 2),
('Cat', 'Chat', 'sha', 'Cat', 'Chat', 'Gato', 'noun', 'm', 'Chat nan ap domi.', 'The cat is sleeping.', 'everyday', 'beginner', ARRAY['animal'], 2),
('Bird', 'Wazo', 'wa-zo', 'Bird', 'Oiseau', 'Pájaro', 'noun', 'm', 'Wazo nan ap vole.', 'The bird is flying.', 'nature', 'beginner', ARRAY['animal'], 2),
('Fish', 'Pwason', 'pwa-son', 'Fish', 'Poisson', 'Pescado', 'noun', 'm', 'Pwason an frèch.', 'The fish is fresh.', 'food', 'beginner', ARRAY['food','sea'], 2),
('Shrimp', 'Kwaz', 'kwaz', 'Shrimp', 'Crevette', 'Camarón', 'noun', 'm', 'Kwaz la bèl.', 'The shrimp is nice.', 'food', 'intermediate', ARRAY['sea','food'], 2),
('Crab', 'Kwab', 'kwab', 'Crab', 'Crabe', 'Cangrejo', 'noun', 'm', 'Kwab la anba wòch.', 'The crab is under the rock.', 'food', 'intermediate', ARRAY['sea'], 2),
('Lobster', 'Omak', 'o-mak', 'Lobster', 'Homard', 'Langosta', 'noun', 'm', 'Omak la cher.', 'Lobster is expensive.', 'food', 'intermediate', ARRAY['sea','luxury'], 2),
('Snail', 'Kagou', 'ka-go', 'Snail', 'Escargot', 'Caracol', 'noun', 'm', 'Kagou la dous.', 'Snail is sweet.', 'food', 'intermediate', ARRAY['food'], 2),
('Soup', 'Bouyon', 'bou-yon', 'Soup / Stew', 'Soupe', 'Sopa', 'noun', 'm', 'Bouyon la cho.', 'The soup is hot.', 'food', 'beginner', ARRAY['dish'], 2),
('Sauce', 'Sos', 'sos', 'Sauce', 'Sauce', 'Salsa', 'noun', 'f', 'Sos la pikan.', 'The sauce is spicy.', 'food', 'beginner', ARRAY['cooking'], 2),
('Fried', 'Frit', 'frit', 'Fried', 'Frit', 'Frito', 'adj', 'mf', 'Poul la frit.', 'The chicken is fried.', 'food', 'beginner', ARRAY['cooking'], 2),
('Boiled', 'Bwi', 'bwi', 'Boiled', 'Bouilli', 'Hervido', 'adj', 'mf', 'Ze a bwi.', 'The egg is boiled.', 'food', 'beginner', ARRAY['cooking'], 2),
('Roasted', 'Roasti', 'ro-as-ti', 'Roasted', 'Rôti', 'Asado', 'adj', 'mf', 'Pwapoul la rosti.', 'The corn is roasted.', 'food', 'intermediate', ARRAY['cooking'], 2),
('Cooked', 'Kwit', 'kwit', 'Cooked', 'Cuit', 'Cocido', 'adj', 'mf', 'Diri a kwit.', 'The rice is cooked.', 'food', 'beginner', ARRAY['cooking'], 2),
('Raw', 'Crud', 'krod', 'Raw', 'Cru', 'Crudo', 'adj', 'mf', 'Pwason an crud.', 'The fish is raw.', 'food', 'intermediate', ARRAY['cooking'], 2),
('Breakfast', 'Dejene', 'de-zhe-ne', 'Breakfast', 'Petit-déjeuner', 'Desayuno', 'noun', 'm', 'Dejene la byen.', 'Breakfast is good.', 'food', 'beginner', ARRAY['meal'], 2),
('Lunch', 'Midyen', 'mi-dyen', 'Lunch', 'Déjeuner', 'Almuerzo', 'noun', 'm', 'Midyen an 12 zè.', 'Lunch is at noon.', 'food', 'beginner', ARRAY['meal'], 2),
('Dinner', 'Swa', 'swa', 'Dinner', 'Dîner', 'Cena', 'noun', 'm', 'Swa la 7 zè.', 'Dinner is at 7.', 'food', 'beginner', ARRAY['meal'], 2),
('Eat', 'Manje', 'man-je', 'To eat', 'Manger', 'Comer', 'verb', 'mf', 'Mwen ap manje.', 'I am eating.', 'everyday', 'beginner', ARRAY['essential','verbs'], 2),
('Drink', 'Bwe', 'bwe', 'To drink', 'Boire', 'Beber', 'verb', 'mf', 'Mwen bwe dlo.', 'I drink water.', 'everyday', 'beginner', ARRAY['essential','verbs'], 2),
('Chew', 'Mache', 'ma-she', 'To chew', 'Mâcher', 'Masticar', 'verb', 'mf', 'Mwen ap mache', 'I am chewing.', 'food', 'intermediate', ARRAY['verbs'], 2),
('Swallow', 'Gile', 'gi-le', 'To swallow', 'Avaler', 'Tragar', 'verb', 'mf', 'Mwen pa kapab gile.', 'I cannot swallow.', 'food', 'intermediate', ARRAY['verbs'], 2),
('Cook', 'Kwit', 'kwit', 'To cook', 'Cuire', 'Cocinar', 'verb', 'mf', 'Fanm nan ap kwit.', 'The woman is cooking.', 'food', 'beginner', ARRAY['verbs'], 2),
('Hungry', 'Disouv', 'di-souv', 'Hungry', 'Affamé', 'Hambriento', 'adj', 'mf', 'Mwen disouv.', 'I am hungry.', 'everyday', 'beginner', ARRAY['feelings'], 2),
('Thirsty', 'Swaf', 'swaf', 'Thirsty', 'Assiette', 'Sediento', 'adj', 'mf', 'Mwen swaf.', 'I am thirsty.', 'everyday', 'beginner', ARRAY['feelings'], 2),
('Full', 'Plen', 'plen', 'Full (吃饱了)', 'Plein', 'Lleno', 'adj', 'mf', 'Vant mwen plen.', 'My stomach is full.', 'everyday', 'beginner', ARRAY['feelings'], 2),
('Delicious', 'Fè', 'fe', 'Delicious', 'Délicieux', 'Delicioso', 'adj', 'mf', 'Manje a fè.', 'The food is delicious.', 'food', 'beginner', ARRAY['taste'], 2),
('Rotten', 'Pouri', 'po-ri', 'Rotten', 'Pourri', 'Podrido', 'adj', 'mf', 'Fwi a pouri.', 'The fruit is rotten.', 'food', 'intermediate', ARRAY['food'], 2),
('Ripe', 'Mouri', 'mo-ri', 'Ripe', 'Mûr', 'Maduro', 'adj', 'mf', 'Bannann la mouri.', 'The banana is ripe.', 'food', 'beginner', ARRAY['food'], 2),
('Hungry', 'Sòk', 'sok', 'Hungry (severe)', 'Affamé', 'Hambriento', 'adj', 'mf', 'Timoun nan sòk.', 'The child is starving.', 'food', 'intermediate', ARRAY['hunger'], 2),
('Kitchen', 'Kwizin', 'kwi-zin', 'Kitchen', 'Cuisine', 'Cocina', 'noun', 'f', 'Kwizin an bèl.', 'The kitchen is beautiful.', 'everyday', 'beginner', ARRAY['house'], 2),
('Plate', 'Plak', 'plak', 'Plate', 'Assiette', 'Plato', 'noun', 'm', 'Plak la kase.', 'The plate is broken.', 'everyday', 'beginner', ARRAY['dishes'], 2),
('Cup', 'Tas', 'tas', 'Cup / Glass', 'Tasse', 'Taza', 'noun', 'm', 'Tas la plen.', 'The cup is full.', 'everyday', 'beginner', ARRAY['dishes'], 2),
('Fork', 'Fòch', 'foch', 'Fork', 'Fourchette', 'Tenedor', 'noun', 'm', 'Fòch la bati.', 'The fork is dirty.', 'everyday', 'intermediate', ARRAY['utensils'], 2),
('Knife', 'Kouto', 'kou-to', 'Knife', 'Couteau', 'Cuchillo', 'noun', 'm', 'Kouto a kout.', 'The knife is sharp.', 'everyday', 'beginner', ARRAY['utensils'], 2),
('Spoon', 'Kiy', 'kiy', 'Spoon', 'Cuillère', 'Cuchara', 'noun', 'm', 'Kiy la long.', 'The spoon is long.', 'everyday', 'beginner', ARRAY['utensils'], 2);

COMMIT;

-- Verify:
-- SELECT count(*) FROM public.dictionary_words WHERE day_added = 2;