-- =====================================================
-- KREYÒL DICTIONARY — Day 3 Bulk Seed
-- Business, Travel, Family, Time, Numbers
-- =====================================================

BEGIN;

-- ======== BUSINESS (60 words) ========
INSERT INTO public.dictionary_words (word, word_creole, pronunciation, translation_english, translation_french, translation_spanish, part_of_speech, gender, example_sentence, example_translation, category, difficulty, tags, day_added) VALUES
('Bank', 'Bank', 'bank', 'Bank', 'Banque', 'Banco', 'noun', 'm', 'Mwen ale nan bank.', 'I am going to the bank.', 'business', 'beginner', ARRAY['finance'], 2),
('Money', 'Lajan', 'la-zhan', 'Money', 'Argent', 'Dinero', 'noun', 'm', 'Lajan an pa ase.', 'The money is not enough.', 'business', 'beginner', ARRAY['essential','finance'], 2),
('Dollar', 'Dola', 'do-la', 'Dollar', 'Dollar', 'Dólar', 'noun', 'm', 'Yon dola.', 'One dollar.', 'business', 'beginner', ARRAY['currency'], 2),
('Cent', 'Sand', 'san', 'Cent', 'Centime', 'Centavo', 'noun', 'm', 'Senk san.', 'Five cents.', 'business', 'beginner', ARRAY['currency'], 2),
('Rich', 'Rich', 'rich', 'Rich', 'Riche', 'Rico', 'adj', 'mf', 'Moun nan rich.', 'The person is rich.', 'business', 'beginner', ARRAY['wealth'], 2),
('Poor', 'Pov', 'pov', 'Poor', 'Pauvre', 'Pobre', 'adj', 'mf', 'Pov a pa gen anyen.', 'The poor person has nothing.', 'business', 'beginner', ARRAY['wealth'], 2),
('Pay', 'Peye', 'pe-ye', 'To pay', 'Payer', 'Pagar', 'verb', 'mf', 'Mwen peye l.', 'I pay for it.', 'business', 'beginner', ARRAY['commerce'], 2),
('Cost', 'Koute', 'kou-te', 'To cost', 'Coûter', 'Costar', 'verb', 'mf', 'Sa a koute anpil.', 'That costs a lot.', 'business', 'beginner', ARRAY['commerce'], 2),
('Cheap', 'Ra', 'ra', 'Cheap', 'Pas cher', 'Barato', 'adj', 'mf', 'Sa a ra.', 'That is cheap.', 'business', 'beginner', ARRAY['price'], 2),
('Expensive', 'Chè', 'she', 'Expensive', 'Cher', 'Caro', 'adj', 'mf', 'Machin nan chè.', 'The car is expensive.', 'business', 'beginner', ARRAY['price'], 2),
('Free', 'Gratis', 'gra-tis', 'Free', 'Gratuit', 'Gratis', 'adj', 'mf', 'Sa se gratis.', 'That is free.', 'business', 'beginner', ARRAY['price'], 2),
('Profit', 'Profit', 'pro-fit', 'Profit', 'Profit', 'Ganancia', 'noun', 'm', 'Profit la gwo.', 'The profit is big.', 'business', 'intermediate', ARRAY['business'], 2),
('Loss', 'Pèd', 'ped', 'Loss', 'Perte', 'Pérdida', 'noun', 'm', 'Pèd la fè mal.', 'The loss hurts.', 'business', 'intermediate', ARRAY['business'], 2),
('Invest', 'Anvesti', 'an-ves-ti', 'To invest', 'Investir', 'Invertir', 'verb', 'mf', 'Mwen vle anvesti.', 'I want to invest.', 'business', 'intermediate', ARRAY['finance'], 2),
('Investor', 'Anvestise', 'an-ves-ti-se', 'Investor', 'Investisseur', 'Inversionista', 'noun', 'm', 'Anvestise a gen lajan.', 'The investor has money.', 'business', 'intermediate', ARRAY['finance'], 2),
('Loan', 'Kredi', 'kre-di', 'Loan / Credit', 'Prêt', 'Préstamo', 'noun', 'm', 'Kredi la difisil.', 'The loan is difficult.', 'business', 'intermediate', ARRAY['finance'], 2),
('Debt', 'Dette', 'de-te', 'Debt', 'Dette', 'Deuda', 'noun', 'f', 'Dette a gro.', 'The debt is big.', 'business', 'intermediate', ARRAY['finance'], 2),
('Save', 'Ede', 'e-de', 'To save', 'Épargner', 'Ahorrar', 'verb', 'mf', 'Mwen ede lajan.', 'I save money.', 'business', 'beginner', ARRAY['finance'], 2),
('Spend', 'ispann', 'is-pen', 'To spend', 'Dépenser', 'Gastar', 'verb', 'mf', 'Mwen depanse anpil.', 'I spend a lot.', 'business', 'beginner', ARRAY['finance'], 2),
('Tax', 'Taks', 'taks', 'Tax', 'Taxe', 'Impuesto', 'noun', 'm', 'Taks la wo.', 'The tax is high.', 'business', 'intermediate', ARRAY['government'], 2),
('Price', 'Pri', 'pri', 'Price', 'Prix', 'Precio', 'noun', 'm', 'Pri an bon.', 'The price is good.', 'business', 'beginner', ARRAY['commerce'], 2),
('Shop', 'Boutik', 'boo-tik', 'Shop / Store', 'Boutique', 'Tienda', 'noun', 'm', 'Boutik la pi.', 'The shop is expensive.', 'business', 'beginner', ARRAY['commerce'], 2),
('Market', 'Mache', 'ma-she', 'Market', 'Marché', 'Mercado', 'noun', 'm', 'Mache a plen.', 'The market is full.', 'business', 'beginner', ARRAY['commerce'], 2),
('Seller', 'Mache', 'ma-she', 'Seller', 'Vendeur', 'Vendedor', 'noun', 'mf', 'Mach an bèl.', 'The seller is nice.', 'business', 'beginner', ARRAY['commerce'], 2),
('Buyer', 'Achte', 'a-sh-te', 'Buyer', 'Acheteur', 'Comprador', 'noun', 'mf', 'Achtè a gen lajan.', 'The buyer has money.', 'business', 'beginner', ARRAY['commerce'], 2),
('Buy', 'Achte', 'a-sh-te', 'To buy', 'Acheter', 'Comprar', 'verb', 'mf', 'Mwen achte l.', 'I buy it.', 'business', 'beginner', ARRAY['essential','verbs'], 2),
('Sell', 'Vann', 'van', 'To sell', 'Vendre', 'Vender', 'verb', 'mf', 'Mwen vann l.', 'I sell it.', 'business', 'beginner', ARRAY['essential','verbs'], 2),
('Trade', 'Komès', 'ko-mes', 'To trade', 'Échanger', 'Comerciar', 'verb', 'mf', 'Nou komès ak peyi lòt.', 'We trade with other countries.', 'business', 'intermediate', ARRAY['commerce'], 2),
('Trade', 'Komès', 'ko-mes', 'Trade / Commerce', 'Commerce', 'Comercio', 'noun', 'm', 'Komès la ale byen.', 'The trade is going well.', 'business', 'intermediate', ARRAY['commerce'], 2),
('Contract', 'Kontra', 'kon-tra', 'Contract', 'Contrat', 'Contrato', 'noun', 'm', 'Kontra a klè.', 'The contract is clear.', 'business', 'intermediate', ARRAY['legal'], 2),
('Sign', 'Sin', 'sin', 'To sign', 'Signer', 'Firmar', 'verb', 'mf', 'Mwen sinyen kontra.', 'I sign the contract.', 'business', 'intermediate', ARRAY['legal'], 2),
('Stamp', 'Tamp', 'tanp', 'Stamp', 'Tampon', 'Sello', 'noun', 'm', 'Tamp la bèl.', 'The stamp is nice.', 'business', 'intermediate', ARRAY['office'], 2),
('Office', 'Biwo', 'bi-wo', 'Office', 'Bureau', 'Oficina', 'noun', 'm', 'Biwo a bèl.', 'The office is beautiful.', 'business', 'beginner', ARRAY['work'], 2),
('Meeting', 'Reyinyon', 're-yi-nyon', 'Meeting', 'Réunion', 'Reunión', 'noun', 'f', 'Reyinyon an 3 zè.', 'The meeting is at 3.', 'business', 'beginner', ARRAY['work'], 2),
('Boss', 'Chèf', 'shef', 'Boss', 'Chef', 'Jefe', 'noun', 'm', 'Chèf la fèm.', 'The boss is strict.', 'business', 'beginner', ARRAY['work'], 2),
('Employee', 'Anplwaye', 'an-plwa-ye', 'Employee', 'Employé', 'Empleado', 'noun', 'm', 'Anplwaye a serye.', 'The employee is serious.', 'business', 'beginner', ARRAY['work'], 2),
('Job', 'Travay', 'tra-vai', 'Job / Work', 'Travail', 'Trabajo', 'noun', 'm', 'Travay la difisil.', 'The job is difficult.', 'business', 'beginner', ARRAY['essential'], 2),
('Salary', 'Salè', 'sa-le', 'Salary', 'Salaire', 'Salario', 'noun', 'm', 'Salè a ba.', 'The salary is low.', 'business', 'beginner', ARRAY['work'], 2),
('Promotion', 'Pwomosyon', 'pro-mo-syon', 'Promotion', 'Promotion', 'Ascenso', 'noun', 'm', 'Pwomosyon an vini.', 'The promotion came.', 'business', 'intermediate', ARRAY['work'], 2),
('Fire', 'Lon', 'lon', 'To fire (someone)', 'Licencier', 'Despedir', 'verb', 'mf', 'Chèf la lwe travayè.', 'The boss fired the worker.', 'business', 'intermediate', ARRAY['work'], 2),
('Hire', 'Kite', 'ki-te', 'To hire', 'Embaucher', 'Contratar', 'verb', 'mf', 'Nou kité yon moun.', 'We hired a person.', 'business', 'intermediate', ARRAY['work'], 2),
('Company', 'Konpayi', 'kon-pa-yi', 'Company', 'Entreprise', 'Empresa', 'noun', 'f', 'Konpayi an gwo.', 'The company is big.', 'business', 'beginner', ARRAY['business'], 2),
('Factory', 'Fabriken', 'fa-bri-ken', 'Factory', 'Usine', 'Fábrica', 'noun', 'm', 'Fabriken an ap travay.', 'The factory is working.', 'business', 'intermediate', ARRAY['industry'], 2),
('Product', 'Pwodui', 'pro-dwi', 'Product', 'Produit', 'Producto', 'noun', 'm', 'Pwodui a bon.', 'The product is good.', 'business', 'beginner', ARRAY['business'], 2),
('Customer', 'Kliyan', 'kli-yan', 'Customer', 'Client', 'Cliente', 'noun', 'm', 'Kliyan an byen.', 'The customer is good.', 'business', 'beginner', ARRAY['commerce'], 2),
('Order', 'Od', 'od', 'Order', 'Commande', 'Pedido', 'noun', 'm', 'Od la vini.', 'The order came.', 'business', 'beginner', ARRAY['commerce'], 2),
('Delivery', 'Livi', 'li-vi', 'Delivery', 'Livraison', 'Entrega', 'noun', 'f', 'Livi a tè', 'The delivery is late.', 'business', 'intermediate', ARRAY['commerce'], 2),
('Warehouse', 'Anbas', 'an-bas', 'Warehouse', 'Entrepôt', 'Almacén', 'noun', 'm', 'Anbas la plen.', 'The warehouse is full.', 'business', 'intermediate', ARRAY['logistics'], 2),
('Truck', 'Kamion', 'ka-mi-on', 'Truck', 'Camion', 'Camión', 'noun', 'm', 'Kamion an vini.', 'The truck came.', 'business', 'beginner', ARRAY['transport'], 2),
('Boat', 'Bato', 'ba-to', 'Boat', 'Bateau', 'Bote', 'noun', 'm', 'Bato an ale.', 'The boat left.', 'travel', 'beginner', ARRAY['transport','sea'], 2),
('Plane', 'Avion', 'a-vi-on', 'Plane', 'Avion', 'Avión', 'noun', 'm', 'Avion nan ap vini.', 'The plane is coming.', 'travel', 'beginner', ARRAY['transport'], 2),
('Airport', 'Ewofò', 'e-wo-fo', 'Airport', 'Aéroport', 'Aeropuerto', 'noun', 'm', 'Ewofò a gwo.', 'The airport is big.', 'travel', 'beginner', ARRAY['transport'], 2),
('Port', 'Pò', 'po', 'Port', 'Port', 'Puerto', 'noun', 'm', 'Pò la plen.', 'The port is full.', 'travel', 'beginner', ARRAY['transport','sea'], 2),
('Passport', 'Paspo', 'pas-po', 'Passport', 'Passeport', 'Pasaporte', 'noun', 'm', 'Paspo mwen fin vye.', 'My passport is expired.', 'travel', 'beginner', ARRAY['travel'], 2),
('Ticket', 'Tike', 'ti-ke', 'Ticket', 'Billets', 'Boleto', 'noun', 'm', 'Tike a chè.', 'The ticket is expensive.', 'travel', 'beginner', ARRAY['travel'], 2),
('Hotel', 'Otèl', 'o-tel', 'Hotel', 'Hôtel', 'Hotel', 'noun', 'm', 'Otèl la bèl.', 'The hotel is beautiful.', 'travel', 'beginner', ARRAY['travel'], 2),
('Room', 'Sal', 'sal', 'Room', 'Chambre', 'Habitación', 'noun', 'm', 'Sal la nèt.', 'The room is clean.', 'travel', 'beginner', ARRAY['accommodation'], 2),
('Reservation', 'Rezève', 're-ze-ve', 'Reservation', 'Réservation', 'Reservación', 'noun', 'f', 'Rezève a fè.', 'The reservation is made.', 'travel', 'intermediate', ARRAY['travel'], 2);

-- ======== TRAVEL (40 words) ========
INSERT INTO public.dictionary_words (word, word_creole, pronunciation, translation_english, translation_french, translation_spanish, part_of_speech, gender, example_sentence, example_translation, category, difficulty, tags, day_added) VALUES
('Airport', 'Ewofò', 'e-wo-fo', 'Airport', 'Aéroport', 'Aeropuerto', 'noun', 'm', 'Ewofò a gwo.', 'The airport is big.', 'travel', 'beginner', ARRAY['transport'], 2),
('Port', 'Pò', 'po', 'Port', 'Port', 'Puerto', 'noun', 'm', 'Pò la plen.', 'The port is full.', 'travel', 'beginner', ARRAY['transport'], 2),
('Bus', 'Bis', 'bis', 'Bus', 'Autobus', 'Autobús', 'noun', 'm', 'Bis la vin.', 'The bus came.', 'travel', 'beginner', ARRAY['transport'], 2),
('Taxi', 'Taksi', 'ta-ksi', 'Taxi', 'Taxi', 'Taxi', 'noun', 'm', 'Taksi a la.', 'The taxi is here.', 'travel', 'beginner', ARRAY['transport'], 2),
('Driver', 'Chofè', 'sho-fe', 'Driver', 'Chauffeur', 'Conductor', 'noun', 'm', 'Chofè a byen.', 'The driver is good.', 'travel', 'beginner', ARRAY['transport'], 2),
('Map', 'Kat', 'kat', 'Map', 'Carte', 'Mapa', 'noun', 'm', 'Kat la fè byen.', 'The map is good.', 'travel', 'beginner', ARRAY['navigation'], 2),
('Address', 'Adres', 'a-dres', 'Address', 'Adresse', 'Dirección', 'noun', 'm', 'Adres la ki?', 'What is the address?', 'travel', 'beginner', ARRAY['location'], 2),
('North', 'Nò', 'no', 'North', 'Nord', 'Norte', 'noun', 'm', 'Nò a fè frèch.', 'The north is cold.', 'travel', 'beginner', ARRAY['directions'], 2),
('South', 'Sid', 'sid', 'South', 'Sud', 'Sur', 'noun', 'm', 'Sid a cho.', 'The south is hot.', 'travel', 'beginner', ARRAY['directions'], 2),
('East', 'Lès', 'les', 'East', 'Est', 'Este', 'noun', 'm', 'Solèy leve nan lès.', 'The sun rises in the east.', 'travel', 'beginner', ARRAY['directions'], 2),
('West', 'Lwès', 'lwes', 'West', 'Ouest', 'Oeste', 'noun', 'm', 'Solèy kouche nan lwès.', 'The sun sets in the west.', 'travel', 'beginner', ARRAY['directions'], 2),
('Go', 'Ale', 'a-le', 'To go', 'Aller', 'Ir', 'verb', 'mf', 'Mwen ale.', 'I am going.', 'everyday', 'beginner', ARRAY['essential','verbs'], 2),
('Come', 'Vini', 'vi-ni', 'To come', 'Venir', 'Venir', 'verb', 'mf', 'Vini la!', 'Come here!', 'everyday', 'beginner', ARRAY['essential','verbs'], 2),
('Arrive', 'rive', 'ri-ve', 'To arrive', 'Arriver', 'Llegar', 'verb', 'mf', 'Mwen rive nan vil la.', 'I arrived at the city.', 'travel', 'beginner', ARRAY['verbs'], 2),
('Leave', 'Pati', 'pa-ti', 'To leave', 'Partir', 'Salir', 'verb', 'mf', 'Bato a pati.', 'The boat left.', 'travel', 'beginner', ARRAY['verbs'], 2),
('Walk', 'Mache', 'ma-she', 'To walk', 'Marcher', 'Caminar', 'verb', 'mf', 'Mwen mache sou wout la.', 'I walk on the road.', 'everyday', 'beginner', ARRAY['verbs'], 2),
('Run', 'Kouri', 'kou-ri', 'To run', 'Courir', 'Correr', 'verb', 'mf', 'Mwen kouri.', 'I run.', 'everyday', 'beginner', ARRAY['verbs'], 2),
('Ride', 'Monte', 'mon-te', 'To ride', 'Monter', 'Montar', 'verb', 'mf', 'Mwen monte sou chwal la.', 'I ride the horse.', 'travel', 'intermediate', ARRAY['verbs'], 2),
('Travel', 'Vwayaje', 'vwa-ya-je', 'To travel', 'Voyager', 'Viajar', 'verb', 'mf', 'Mwen vwayaje anpil.', 'I travel a lot.', 'travel', 'beginner', ARRAY['verbs'], 2),
('Trip', 'Vwayaj', 'vwa-yazh', 'Trip', 'Voyage', 'Viaje', 'noun', 'm', 'Vwayaj la bèl.', 'The trip is beautiful.', 'travel', 'beginner', ARRAY['travel'], 2),
('Tourist', 'Touris', 'tu-ris', 'Tourist', 'Touriste', 'Turista', 'noun', 'm', 'Touris an plis.', 'There are more tourists.', 'travel', 'beginner', ARRAY['tourism'], 2),
('Guide', 'Gid', 'gid', 'Guide', 'Guide', 'Guía', 'noun', 'mf', 'Gid la byen konprann.', 'The guide understands well.', 'travel', 'intermediate', ARRAY['tourism'], 2),
('Border', 'Bòd', 'bo', 'Border', 'Frontière', 'Frontera', 'noun', 'm', 'Bòd la fèmen.', 'The border is closed.', 'travel', 'intermediate', ARRAY['government'], 2),
('Visa', 'Viza', 'vi-za', 'Visa', 'Visa', 'Visa', 'noun', 'm', 'Viza a difisil jwenn.', 'The visa is hard to get.', 'travel', 'intermediate', ARRAY['travel'], 2),
('Customs', 'Douannen', 'dou-a-nen', 'Customs', 'Douanes', 'Aduanas', 'noun', 'f', 'Douannen an debou.', 'Customs is busy.', 'travel', 'intermediate', ARRAY['travel'], 2),
('Luggage', 'Machandiz', 'ma-shan-diz', 'Luggage', 'Bagages', 'Equipaje', 'noun', 'm', 'Machandiz la piti.', 'The luggage is small.', 'travel', 'beginner', ARRAY['travel'], 2),
('Lost', 'Pèdi', 'pe-di', 'Lost', 'Perdu', 'Perdido', 'adj', 'mf', 'Mwen pèdi.', 'I am lost.', 'travel', 'beginner', ARRAY['problems'], 2),
('Find', 'Jwen', 'zwen', 'To find', 'Trouver', 'Encontrar', 'verb', 'mf', 'Mwen jwen li.', 'I found it.', 'everyday', 'beginner', ARRAY['verbs'], 2),
('Wait', 'Tan', 'tan', 'To wait', 'Attendre', 'Esperar', 'verb', 'mf', 'Mwen tan mwen.', 'I wait for it.', 'everyday', 'beginner', ARRAY['verbs'], 2),
('Visit', 'Vizite', 'vi-zi-te', 'To visit', 'Visiter', 'Visitar', 'verb', 'mf', 'Mwen vizite fanmi mwen.', 'I visit my family.', 'travel', 'beginner', ARRAY['verbs'], 2),
('Hotel', 'Otèl', 'o-tel', 'Hotel', 'Hôtel', 'Hotel', 'noun', 'm', 'Otèl la bèl.', 'The hotel is beautiful.', 'travel', 'beginner', ARRAY['accommodation'], 2),
('Beach', 'Plasaj', 'pla-sazh', 'Beach', 'Plage', 'Playa', 'noun', 'm', 'Plasaj la bèl.', 'The beach is beautiful.', 'nature', 'beginner', ARRAY['nature','tourism'], 2),
('Mountain', 'Mòn', 'mon', 'Mountain', 'Montagne', 'Montaña', 'noun', 'm', 'Mòn nan wo.', 'The mountain is high.', 'nature', 'beginner', ARRAY['nature'], 2),
('River', 'rivyè', 'ri-vye', 'River', 'Rivière', 'Río', 'noun', 'm', 'Rivyè a koule.', 'The river flows.', 'nature', 'beginner', ARRAY['nature'], 2),
('Sea', 'Lanmè', 'lan-me', 'Sea / Ocean', 'Mer', 'Mar', 'noun', 'f', 'Lanmè a gwo.', 'The sea is big.', 'nature', 'beginner', ARRAY['nature','sea'], 2),
('Island', 'Il', 'il', 'Island', 'Île', 'Isla', 'noun', 'm', 'Il a bèl.', 'The island is beautiful.', 'nature', 'intermediate', ARRAY['geography'], 2),
('Hill', 'Tibò', 'ti-bo', 'Hill', 'Colline', 'Colina', 'noun', 'm', 'Tibò a wo.', 'The hill is high.', 'nature', 'intermediate', ARRAY['geography'], 2),
('Forest', 'Bwa', 'bwa', 'Forest / Woods', 'Forêt', 'Bosque', 'noun', 'm', 'Bwa a fon.', 'The forest is deep.', 'nature', 'beginner', ARRAY['nature'], 2),
('Tree', 'Pyebwa', 'pye-bwa', 'Tree', 'Arbre', 'Árbol', 'noun', 'm', 'Pyebwa a gwo.', 'The tree is big.', 'nature', 'beginner', ARRAY['nature'], 2);

-- ======== TIME (30 words) ========
INSERT INTO public.dictionary_words (word, word_creole, pronunciation, translation_english, translation_french, translation_spanish, part_of_speech, gender, example_sentence, example_translation, category, difficulty, tags, day_added) VALUES
('Today', 'Jodi a', 'zho-di a', 'Today', "Aujourd'hui", 'Hoy', 'noun', 'm', 'Jodi a se yon bèl jou.', 'Today is a beautiful day.', 'time', 'beginner', ARRAY['essential','time'], 2),
('Yesterday', 'Yè', 'ye', 'Yesterday', 'Hier', 'Ayer', 'noun', 'm', 'Yè te difisil.', 'Yesterday was difficult.', 'time', 'beginner', ARRAY['time'], 2),
('Tomorrow', 'Demen', 'de-men', 'Tomorrow', 'Demain', 'Mañana', 'noun', 'm', 'Demen ap vin.', 'Tomorrow will come.', 'time', 'beginner', ARRAY['essential','time'], 2),
('Now', 'Kounya', 'kou-nya', 'Now', 'Maintenant', 'Ahora', 'adv', 'mf', 'Kounya mwen la.', 'Now I am here.', 'time', 'beginner', ARRAY['time'], 2),
('Later', 'Pita', 'pi-ta', 'Later', 'Plus tard', 'Después', 'adv', 'mf', 'Pita nap pale.', 'Later we will talk.', 'time', 'beginner', ARRAY['time'], 2),
('Soon', 'Byento', 'byen-to', 'Soon', 'Bientôt', 'Pronto', 'adv', 'mf', 'Byento nap wè.', 'We will see soon.', 'time', 'beginner', ARRAY['time'], 2),
('Morning', 'Matin', 'ma-tin', 'Morning', 'Matin', 'Mañana', 'noun', 'm', 'Matin an bon.', 'The morning is good.', 'time', 'beginner', ARRAY['time'], 2),
('Afternoon', 'Apre midi', 'a-pre mi-di', 'Afternoon', 'Après-midi', 'Tarde', 'noun', 'm', 'Apre midi mwen travay.', 'In the afternoon I work.', 'time', 'beginner', ARRAY['time'], 2),
('Evening', 'Aswè', 'a-swe', 'Evening', 'Soir', 'Noche', 'noun', 'm', 'Aswè la bèl.', 'The evening is beautiful.', 'time', 'beginner', ARRAY['time'], 2),
('Night', 'Nwit', 'nwit', 'Night', 'Nuit', 'Noche', 'noun', 'f', 'Nwit la fèk komanse.', 'The night just started.', 'time', 'beginner', ARRAY['essential','time'], 2),
('Hour', 'Lè', 'le', 'Hour', 'Heure', 'Hora', 'noun', 'm', 'Yon lè a rete.', 'One hour left.', 'time', 'beginner', ARRAY['time'], 2),
('Minute', 'Minit', 'mi-nit', 'Minute', 'Minute', 'Minuto', 'noun', 'm', 'Yon minit paske.', 'Just a minute.', 'time', 'beginner', ARRAY['time'], 2),
('Second', 'Segonn', 'se-gon', 'Second', 'Seconde', 'Segundo', 'noun', 'm', 'Yon segonn!', 'One second!', 'time', 'beginner', ARRAY['time'], 2),
('Week', 'Semèn', 'se-men', 'Week', 'Semaine', 'Semana', 'noun', 'm', 'Yon semèn a pase.', 'A week passed.', 'time', 'beginner', ARRAY['time'], 2),
('Month', 'Mwa', 'mwa', 'Month', 'Mois', 'Mes', 'noun', 'm', 'Mwa a fin pase.', 'The month passed.', 'time', 'beginner', ARRAY['time'], 2),
('Year', 'Lane', 'la-ne', 'Year', 'Année', 'Año', 'noun', 'm', 'Lane a te bèl.', 'The year was good.', 'time', 'beginner', ARRAY['essential','time'], 2),
('Monday', 'Lendi', 'len-di', 'Monday', 'Lundi', 'Lunes', 'noun', 'm', 'Lendi mwen travay.', 'Monday I work.', 'time', 'beginner', ARRAY['days'], 2),
('Tuesday', 'Madi', 'ma-di', 'Tuesday', 'Mardi', 'Martes', 'noun', 'm', 'Madi se yon bèl jou.', 'Tuesday is a beautiful day.', 'time', 'beginner', ARRAY['days'], 2),
('Wednesday', 'Mèkredi', 'me-kre-di', 'Wednesday', 'Mercredi', 'Miércoles', 'noun', 'm', 'Mèkredi mwen vizite.', 'Wednesday I visit.', 'time', 'beginner', ARRAY['days'], 2),
('Thursday', 'Jedi', 'zhe-di', 'Thursday', 'Jeudi', 'Jueves', 'noun', 'm', 'Jedi se bèl jou.', 'Thursday is a good day.', 'time', 'beginner', ARRAY['days'], 2),
('Friday', 'Vandredi', 'van-dre-di', 'Friday', 'Vendredi', 'Viernes', 'noun', 'm', 'Vandredi a bon.', 'Friday is good.', 'time', 'beginner', ARRAY['days'], 2),
('Saturday', 'Samdi', 'sam-di', 'Saturday', 'Samedi', 'Sábado', 'noun', 'm', 'Samdi nap repos.', 'Saturday we rest.', 'time', 'beginner', ARRAY['days'], 2),
('Sunday', 'Dimanch', 'di-manch', 'Sunday', 'Dimanche', 'Domingo', 'noun', 'm', 'Dimanch mwen ale legliz.', 'Sunday I go to church.', 'time', 'beginner', ARRAY['days'], 2),
('January', 'Janvye', 'zhan-vye', 'January', 'Janvier', 'Enero', 'noun', 'm', 'Janvye se mwa fwa.', 'January is a cold month.', 'time', 'beginner', ARRAY['months'], 2),
('February', 'Fevriye', 'fev-ri-ye', 'February', 'Février', 'Febrero', 'noun', 'm', 'Fevriye se mwa kout.', 'February is a short month.', 'time', 'beginner', ARRAY['months'], 2),
('March', 'Mas', 'mas', 'March', 'Mars', 'Marzo', 'noun', 'm', 'Mas se bèl mwa.', 'March is a beautiful month.', 'time', 'beginner', ARRAY['months'], 2),
('April', 'Avril', 'a-vril', 'April', 'Avril', 'Abril', 'noun', 'm', 'Avril pli vini.', 'April rain comes.', 'time', 'beginner', ARRAY['months'], 2),
('May', 'Me', 'me', 'May', 'Mai', 'Mayo', 'noun', 'm', 'Me se mwa cho.', 'May is a hot month.', 'time', 'beginner', ARRAY['months'], 2),
('June', 'Jen', 'zhen', 'June', 'Juin', 'Junio', 'noun', 'm', 'Jen se mwa bèl.', 'June is a beautiful month.', 'time', 'beginner', ARRAY['months'], 2),
('Always', 'Toujou', 'tou-zhou', 'Always', 'Toujours', 'Siempre', 'adv', 'mf', 'Mwen toujou la.', 'I am always here.', 'time', 'beginner', ARRAY['time'], 2),
('Never', 'Janme', 'zhan-me', 'Never', 'Jamais', 'Nunca', 'adv', 'mf', 'Mwen pa janme bliye.', 'I never forget.', 'time', 'beginner', ARRAY['time'], 2),
('Again', 'Anko', 'an-ko', 'Again', 'Encore', 'Otra vez', 'adv', 'mf', 'Fè l anko.', 'Do it again.', 'time', 'beginner', ARRAY['time'], 2);

COMMIT;

-- Verify:
-- SELECT count(*) FROM public.dictionary_words WHERE day_added = 2;